postgres:
  image: postgres:alpine
  environment:
    POSTGRES_PASSWORD: "pass"
    POSTGRES_USER: "postgres"
  expose:
    - "5432"
  ports:
    - "5432:5432"

web:
  build: .
  links:
    - postgres
  expose:
    - "4000"
  ports:
    - "4000:4000"
  working_dir: /var/www/coffee-maker
  volumes:
    - .:/var/www/coffee-maker
  entrypoint:
    - /root/start_services.sh